[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | \.env.prod
  | env
  | venv
  | _build
  | buck-out
  | build
  | dist
  | __pycache__
  | temp
  | jenkins_home
)/
'''