"""update

Revision ID: dfedff0fd712
Revises: c7b030659e36
Create Date: 2020-11-24 03:40:47.747218

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dfedff0fd712"
down_revision = "c7b030659e36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("test2", sa.String(length=15), nullable=True))
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.drop_column("movies", "test2")
    # ### end Alembic commands ###
